### PR TITLE
closing request in order to remove TempFileCache

### PR DESCRIPTION
**Pull request by aponb**

### CODE REVIEW

**Comment by anjackson** [comment]
I'm not sure what problems you're seeing, but unfortunately this patch is not acceptable as it is. This class implements `org.apache.tika.detect.Detector` and as per [the API documentation](https://tika.apache.org/1.2/api/org/apache/tika/detect/Detector.html):

> ... The stream must not be closed by the detector. 

i.e. it's up to the caller to call `.close()` on the original InputStream, not our `Detector`. Whereas your patch closes the `InputStreamIdentificationRequest` wrapper, and this also closes the wrapped stream.

**Comment by aponb** [comment]
> I'm not sure what problems you're seeing, but unfortunately this patch is not acceptable as it is. This class implements `org.apache.tika.detect.Detector` and as per [the API documentation](https://tika.apache.org/1.2/api/org/apache/tika/detect/Detector.html):
> 
> > ... The stream must not be closed by the detector.
> 
> i.e. it's up to the caller to call `.close()` on the original InputStream, not our `Detector`. Whereas your patch closes the `InputStreamIdentificationRequest` wrapper, and this also closes the wrapped stream.

Thanks for pointing to this. So closing on this position is definitely wrong. Sorry for that. What I've tried to solve is to remove a not delete TempFileCache which is created by the open() method of InputStreamIdentificationRequest. I saw the only possibility to delete the Cache in calling request.close() in order to call close() in base class of InputStreamReader the AbstractReader which removes the cache. Actually I am using the https://github.com/ukwa/webarchive-discovery/tree/master/warc-indexer and after running it many thousand "nanite-tmp" directories stay in the temp directory. Most of them I could get rid by applying https://github.com/openpreserve/nanite/pull/39 (maybe this is also wrong) but then there were still a lot of "byteseek" tmpfiles in "nanite-tmp" folder, which were created by TempFileCache via InputStreamIdenticationRequest. What can I do to remove correctly this TempFileCaches? If this is already off Topic, then please excuse me and ignore it. Thank you.

**Comment by anjackson** [comment]
Hm, I think the right solution is a slightly more complex change.  I think we need to push the handling of the temporary directory down into the `InputStreamIdentificationRequest` class itself.  

Rather than the client creating the temp folder and [passing it in via the constructor](
https://github.com/openpreserve/nanite/blob/b6d313774ff036b0bc4013facc3b0cf10cb85a64/nanite-core/src/main/java/uk/bl/wa/nanite/droid/InputStreamIdentificationRequest.java#L44), I think we'll need to create it directly inside that constructor class. If each `InputStreamIdentificationRequest` manages it's own temp folder, then it can attempt to clean up when the `close()` method is called, and maybe add a `finalizer` that tries to ensure the temp folder is removed when the object is garbage collected.

I'm about to go on holiday for a week or so, so I'm afraid I won't get change to look at it for a while. Sorry about that.

**Comment by aponb** [comment]
Thanks for the hint. I am going to try such a solution. Happy Holidays!

**Comment by aponb** [comment]
Now I moved the handling of "nanite-tmp" inside [InputStreamIdentificationRequest](https://github.com/aponb/nanite/blob/58d877061d138fba268c68c6b916786149b1d4cb/nanite-core/src/main/java/uk/bl/wa/nanite/droid/InputStreamIdentificationRequest.java). I wanted to avoid using a finalize method and added a [removeTempDir-Method](https://github.com/aponb/nanite/blob/58d877061d138fba268c68c6b916786149b1d4cb/nanite-core/src/main/java/uk/bl/wa/nanite/droid/InputStreamIdentificationRequest.java#L82 ) which will be called inside [close](https://github.com/aponb/nanite/blob/58d877061d138fba268c68c6b916786149b1d4cb/nanite-core/src/main/java/uk/bl/wa/nanite/droid/InputStreamIdentificationRequest.java#L75) and called [directly](https://github.com/aponb/nanite/blob/58d877061d138fba268c68c6b916786149b1d4cb/nanite-core/src/main/java/uk/bl/wa/nanite/droid/DroidDetector.java#L439) when close of InputStreamIdentificationRequest was not used.

**Comment by anjackson** [comment]
Excellent, thanks. I'll review it more closely shortly.

I think this supercedes #39, yes?

**Comment by aponb** [comment]
Yes. This is obsolete now.

**Comment by anjackson** [comment]
Thanks again!

**Pull request merged**
