### PR TITLE
close two file descriptor leaks

### PR DESCRIPTION
**Pull request by rsehr**
This fix closes two file descriptor leaks in DroidDetector.detectPUIDs

### CODE REVIEW

**Comment by anjackson** [comment]
Thanks for this!  Unfortunately, I'm having trouble working out what's changed because your editing has also converted all the spaces to tabs, so I'm unable to review the actual changes.  Could you possibly undo the space->tab conversion?

**Comment by rsehr** [comment]
I don't have the project checked out any more, but I found the difference. It is in DroidDetector.java line 364ff

**Comment by anjackson** [comment]
Okay, so following merging #40 some of the code here was out of date. I believe I've merged in the changes, although they are still mostly formatting related. The crucial part seems to be slightly more careful handling of stream closing in `detectPUIDs(File file)`.

**Comment by anjackson** [comment]
Damn, the sig file version regression slipped past me.  Fixed in 479ba31

**Pull request merged**
